services:
  capture-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: capture
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: video
    ports:
      - 5432:5432
    volumes:
      - capture-db-data:/var/lib/postgresql/data
      - .docker/postgresql/volumes/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
  capture-db-data:
