@host = http://localhost:3000

###

POST {{host}}/api/users HTTP/1.1
content-type: application/json

{
    "username": "pault",
    "password": "secret"
}

###

GET {{host}}/api/users/37b2e3a1-8446-47e4-89ec-1d36e5b351fd HTTP/1.1
content-type: text/plain; charset=utf-8

###

GET {{host}}/api/users HTTP/1.1
content-type: text/plain; charset=utf-8
