[api]
local_ip = '0.0.0.0'
port = 3000

[media]
enabled = false
recording_duration = 20
output_folder = 'output'

[datasource]
enabled = true
type = 'postgres'
host = 'localhost'
port = 5432
database = 'capture'